"""initial 6 tables

Revision ID: 41f63c59da2d
Revises: 
Create Date: 2026-07-03 21:51:17.792463
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '41f63c59da2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('page_type', sa.Text(), nullable=False),
    sa.Column('render_js', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'page_type', name='uq_domain_host_pagetype')
    )
    op.create_table('config_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['upload_file.id'], name='fk_cv_source_file', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'version', name='uq_configversion_domain_ver')
    )
    op.create_table('upload_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('config_version_id', sa.UUID(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['config_version.id'], name='fk_batch_config_version', use_alter=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('dom_skeleton_hash', sa.String(), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parse_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('config_version_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['config_version.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['upload_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_result')
    op.drop_table('upload_file')
    op.drop_table('job')
    op.drop_table('upload_batch')
    op.drop_table('config_version')
    op.drop_table('domain')
    # ### end Alembic commands ###
